#!/usr/bin/env python3

import sys
import os.path as path
import random

DEFAULT_ZSIG_FILE = "~/.owl/zsigs"

def main(zsig_file):
    with open(zsig_file) as f:
        zsigs = [l for l in f if l != "\n"]
        print(random.choice(zsigs), end="")

if __name__=="__main__":
    filename = DEFAULT_ZSIG_FILE if len(sys.argv) == 1 else sys.argv[1]
    main(path.realpath(path.expanduser(filename)))
